[package]
name = "gaw-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "gaw"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
gaw-audio = { path = "../gaw-audio" }
gaw-core = { path = "../gaw-core" }
gaw-project = { path = "../gaw-project" }
serde_json.workspace = true

[lints]
workspace = true

